sudo: required
services:
  - docker

before_install: 
  - docker build -t csabi/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run csabi/docker-react-tutorial npm run test -- --coverage