FROM node:16-alpine

WORKDIR '/app'

COPY --chown=node:node package.json .
RUN npm install

COPY --chown=node:node . .
USER node

RUN chmod 777 /app/node_modules

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

CMD [ "npm", "run", "start" ]